version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Install
          command: yarn
      - run:
          name: Bootstrap
          command: yarn bootstrap 
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
   
      - run:
          name: Deployment
          command: |
            if [[  "$CIRCLE_BRANCH" == 'master' ]]; then
              echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
              VERSION=$(cat lerna.json | jq .version --raw-output)
              ./node_modules/.bin/lerna publish --skip-git --repo-version $VERSION --yes --force-publish=* --npm-client=npm
            fi