version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install
          command: yarn
      - run:
          name: Bootstrap
          command: yarn bootstrap 
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
      
      - run:
          name: Build Docker
          command: |
            if [[  "$CIRCLE_BRANCH" == 'master' ]]; then
              docker build -t developmentseed/lambda-ecs-runner:latest task-runner
            fi


      - run:
          name: Deployment
          command: |
            if [[  "$CIRCLE_BRANCH" == 'master' ]]; then
              echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
              VERSION=$(cat lerna.json | jq .version --raw-output)
              ./node_modules/.bin/lerna publish --skip-git --repo-version $VERSION --yes --force-publish=* --npm-client=npm


              # publish docker images
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              docker push developmentseed/lambda-ecs-runner:latest
            
              docker tag developmentseed/lambda-ecs-runner:latest developmentseed/lambda-ecs-runner:node-8.11-$VERSION
              docker push developmentseed/lambda-ecs-runner:node-8.11-$VERSION
            fi